In [5]:
import pandas as pd
df = pd.DataFrame({
    "name": [
        "Aarav Sharma","Riya Verma","Vivaan Mehta","Anaya Gupta","Ishaan Rao",
        "Diya Singh","Kabir Nair","Myra Jain","Arjun Patel","Sara Ali",
        "Krish Pillai","Anvi Desai","Om Bansal","Tara Kapoor","Reyansh Yadav",
        "Aadhya Saxena","Advik Kulkarni","Saanvi Shetty","Rudra Khatri","Kiara Joshi",
        "Harsh Tiwari","Meera Menon","Laksh Malhotra","Navya Reddy","Shaurya Sethi",
        "Aarohi Das","Dev Thakur","Inaaya Khan","Yug Arora","Pari Basu",
        "Manan Vora","Amaira Paul","Atharv Sinha","Vanya Bhat","Aryan Gokhale",
        "Shanaya Roy","Pranav Chopra","Zara Qureshi","Nivaan Kohli","Kavya Iyer",
        "Arham Gill","Riddhi Chatterjee","Hridaan Garg","Mahika Puri","Shivansh Bhatt",
        "Tanishka Rao","Ayaan D’Souza","Trisha Jha","Kiaan Oberoi","Nisha Solanki"
    ],

    "class": [
        10,9,8,7,10,9,8,7,10,9,
        8,7,10,9,8,7,10,9,8,7,
        10,9,8,7,10,9,8,7,10,9,
        8,7,10,9,8,7,10,9,8,7,
        10,9,8,7,10,9,8,7,10,9
    ],

    "age": [
        15,14,13,12,15,14,13,12,16,14,
        13,12,15,14,13,12,15,14,13,12,
        16,14,13,12,15,14,13,12,15,14,
        13,12,16,14,13,12,15,14,13,12,
        16,14,13,12,15,14,13,12,16,14
    ],

    "gender": [
        "M","F","M","F","M","F","M","F","M","F",
        "M","F","M","F","M","F","M","F","M","F",
        "M","F","M","F","M","F","M","F","M","F",
        "M","F","M","F","M","F","M","F","M","F",
        "M","F","M","F","M","F","M","F","M","F"
    ],

    "marks": [
        92,88,76,95,81,67,72,89,78,93,
        85,91,74,98,69,87,96,77,82,90,
        63,85,92,73,89,94,71,86,79,64,
        83,97,88,75,62,80,91,84,77,93,
        68,88,90,82,74,95,87,79,83,92
    ],

    "grade": [
        "A","B+","C+","A+","B","D+","C","B+","C+","A",
        "B+","A","C","A+","D+","B","A+","C+","B","A-",
        "D","B+","A","C","B+","A","C","B","C+","D",
        "B","A+","B+","C+","D","B-","A","B","C+","A",
        "D+","B+","A-","B","C","A+","B","C+","B","A"
    ]
})

print(df)

                 name  class  age gender  marks grade
0        Aarav Sharma     10   15      M     92     A
1          Riya Verma      9   14      F     88    B+
2        Vivaan Mehta      8   13      M     76    C+
3         Anaya Gupta      7   12      F     95    A+
4          Ishaan Rao     10   15      M     81     B
5          Diya Singh      9   14      F     67    D+
6          Kabir Nair      8   13      M     72     C
7           Myra Jain      7   12      F     89    B+
8         Arjun Patel     10   16      M     78    C+
9            Sara Ali      9   14      F     93     A
10       Krish Pillai      8   13      M     85    B+
11         Anvi Desai      7   12      F     91     A
12          Om Bansal     10   15      M     74     C
13        Tara Kapoor      9   14      F     98    A+
14      Reyansh Yadav      8   13      M     69    D+
15      Aadhya Saxena      7   12      F     87     B
16     Advik Kulkarni     10   15      M     96    A+
17      Saanvi Shetty      9   14      F     77    C+
18       Rudra Khatri      8   13      M     82     B
19        Kiara Joshi      7   12      F     90    A-
20       Harsh Tiwari     10   16      M     63     D
21        Meera Menon      9   14      F     85    B+
22     Laksh Malhotra      8   13      M     92     A
23        Navya Reddy      7   12      F     73     C
24      Shaurya Sethi     10   15      M     89    B+
25         Aarohi Das      9   14      F     94     A
26         Dev Thakur      8   13      M     71     C
27        Inaaya Khan      7   12      F     86     B
28          Yug Arora     10   15      M     79    C+
29          Pari Basu      9   14      F     64     D
30         Manan Vora      8   13      M     83     B
31        Amaira Paul      7   12      F     97    A+
32       Atharv Sinha     10   16      M     88    B+
33         Vanya Bhat      9   14      F     75    C+
34      Aryan Gokhale      8   13      M     62     D
35        Shanaya Roy      7   12      F     80    B-
36      Pranav Chopra     10   15      M     91     A
37       Zara Qureshi      9   14      F     84     B
38       Nivaan Kohli      8   13      M     77    C+
39         Kavya Iyer      7   12      F     93     A
40         Arham Gill     10   16      M     68    D+
41  Riddhi Chatterjee      9   14      F     88    B+
42       Hridaan Garg      8   13      M     90    A-
43        Mahika Puri      7   12      F     82     B
44     Shivansh Bhatt     10   15      M     74     C
45       Tanishka Rao      9   14      F     95    A+
46      Ayaan D’Souza      8   13      M     87     B
47         Trisha Jha      7   12      F     79    C+
48       Kiaan Oberoi     10   16      M     83     B
49      Nisha Solanki      9   14      F     92     A

In [6]:
df.head()

           name  class  age gender  marks grade
0  Aarav Sharma     10   15      M     92     A
1    Riya Verma      9   14      F     88    B+
2  Vivaan Mehta      8   13      M     76    C+
3   Anaya Gupta      7   12      F     95    A+
4    Ishaan Rao     10   15      M     81     B

In [7]:
df.tail()

             name  class  age gender  marks grade
45   Tanishka Rao      9   14      F     95    A+
46  Ayaan D’Souza      8   13      M     87     B
47     Trisha Jha      7   12      F     79    C+
48   Kiaan Oberoi     10   16      M     83     B
49  Nisha Solanki      9   14      F     92     A

In [8]:
df.shape

(50, 6)

In [9]:
df.shape

(50, 6)

In [10]:
df.columns

Index(['name', 'class', 'age', 'gender', 'marks', 'grade'], dtype='object')

In [11]:
df.columns

Index(['name', 'class', 'age', 'gender', 'marks', 'grade'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    50 non-null     object
 1   class   50 non-null     int64
 2   age     50 non-null     int64
 3   gender  50 non-null     object
 4   marks   50 non-null     int64
 5   grade   50 non-null     object
dtypes: int64(3), object(3)
memory usage: 1.8+ KB

In [13]:
df.describe()

           class        age      marks
count  50.000000  50.000000  50.000000
mean    8.540000  13.640000  82.880000
std     1.128662   1.289835   9.612152
min     7.000000  12.000000  62.000000
25%     8.000000  13.000000  76.250000
50%     9.000000  14.000000  84.500000
75%     9.750000  14.750000  90.750000
max    10.000000  16.000000  98.000000

In [14]:
df.index

RangeIndex(start=0, stop=50, step=1)

In [15]:
df.dtypes

name      object
class      int64
age        int64
gender    object
marks      int64
grade     object
dtype: object

In [16]:
df.memory_usage()

Index      72
name      200
class     400
age       400
gender    200
marks     400
grade     200
dtype: int64

In [17]:
df.nunique()

name      50
class      4
age        5
gender     2
marks     34
grade     10
dtype: int64

In [18]:
cf = pd.read_csv("pandasdata.csv")
print(cf)

    Product Name        Category   Region       City     Sales    Price  \
0         Camera     Electronics     West    Kolkata  46947.67   797.33
1     Headphones  Home Appliance  Central  Hyderabad  42089.11  2238.05
2       Keyboard     Accessories     West    Kolkata  35192.00  4528.89
3       Keyboard  Home Appliance    North    Kolkata  19937.50  3969.36
4             TV  Home Appliance    North      Delhi       NaN  1333.62
..           ...             ...      ...        ...       ...      ...
994          NaN             NaN      NaN        NaN       NaN      NaN
995          NaN             NaN      NaN        NaN       NaN      NaN
996          NaN             NaN      NaN        NaN       NaN      NaN
997          NaN             NaN      NaN        NaN       NaN      NaN
998          NaN             NaN      NaN        NaN       NaN      NaN

      Profit
0    1733.15
1    1146.45
2     503.32
3     257.27
4    5011.02
..       ...
994      NaN
995      NaN
996      NaN
997      NaN
998      NaN

[999 rows x 7 columns]

In [19]:
cf = pd.read_csv("pandasdata.csv")
print(cf)

    Product Name        Category   Region       City     Sales    Price  \
0         Camera     Electronics     West    Kolkata  46947.67   797.33
1     Headphones  Home Appliance  Central  Hyderabad  42089.11  2238.05
2       Keyboard     Accessories     West    Kolkata  35192.00  4528.89
3       Keyboard  Home Appliance    North    Kolkata  19937.50  3969.36
4             TV  Home Appliance    North      Delhi       NaN  1333.62
..           ...             ...      ...        ...       ...      ...
994          NaN             NaN      NaN        NaN       NaN      NaN
995          NaN             NaN      NaN        NaN       NaN      NaN
996          NaN             NaN      NaN        NaN       NaN      NaN
997          NaN             NaN      NaN        NaN       NaN      NaN
998          NaN             NaN      NaN        NaN       NaN      NaN

      Profit
0    1733.15
1    1146.45
2     503.32
3     257.27
4    5011.02
..       ...
994      NaN
995      NaN
996      NaN
997      NaN
998      NaN

[999 rows x 7 columns]

In [20]:
cf = pd.read_csv("pandasdata.csv")
print(cf)

    Product Name        Category   Region       City     Sales    Price  \
0         Camera     Electronics     West    Kolkata  46947.67   797.33
1     Headphones  Home Appliance  Central  Hyderabad  42089.11  2238.05
2       Keyboard     Accessories     West    Kolkata  35192.00  4528.89
3       Keyboard  Home Appliance    North    Kolkata  19937.50  3969.36
4             TV  Home Appliance    North      Delhi       NaN  1333.62
..           ...             ...      ...        ...       ...      ...
994          NaN             NaN      NaN        NaN       NaN      NaN
995          NaN             NaN      NaN        NaN       NaN      NaN
996          NaN             NaN      NaN        NaN       NaN      NaN
997          NaN             NaN      NaN        NaN       NaN      NaN
998          NaN             NaN      NaN        NaN       NaN      NaN

      Profit
0    1733.15
1    1146.45
2     503.32
3     257.27
4    5011.02
..       ...
994      NaN
995      NaN
996      NaN
997      NaN
998      NaN

[999 rows x 7 columns]

In [21]:
cf.shape

(999, 7)

In [22]:
cf.memory_usage()

Index             72
Product Name    3996
Category        3996
Region          3996
City            3996
Sales           7992
Price           7992
Profit          7992
dtype: int64

In [23]:
cf.tail()

    Product Name Category Region City  Sales  Price  Profit
994          NaN      NaN    NaN  NaN    NaN    NaN     NaN
995          NaN      NaN    NaN  NaN    NaN    NaN     NaN
996          NaN      NaN    NaN  NaN    NaN    NaN     NaN
997          NaN      NaN    NaN  NaN    NaN    NaN     NaN
998          NaN      NaN    NaN  NaN    NaN    NaN     NaN

In [24]:
cf.head()

  Product Name        Category   Region       City     Sales    Price   Profit
0       Camera     Electronics     West    Kolkata  46947.67   797.33  1733.15
1   Headphones  Home Appliance  Central  Hyderabad  42089.11  2238.05  1146.45
2     Keyboard     Accessories     West    Kolkata  35192.00  4528.89   503.32
3     Keyboard  Home Appliance    North    Kolkata  19937.50  3969.36   257.27
4           TV  Home Appliance    North      Delhi       NaN  1333.62  5011.02

In [25]:
cf.isnull().sum()

Product Name    849
Category        849
Region          851
City            849
Sales           855
Price           851
Profit          849
dtype: int64

In [26]:
cf["City"].isnull().sum()

np.int64(849)

In [27]:
cf.isnull().sum()

Product Name    849
Category        849
Region          851
City            849
Sales           855
Price           851
Profit          849
dtype: int64

In [28]:
cf.sort_values('Sales')

    Product Name     Category Region       City    Sales    Price   Profit
94        Tablet  Accessories   East     Mumbai  1243.97  2987.03  1311.70
72    Smartphone    Computing  South    Kolkata  1279.46  3026.41  1701.38
132     Keyboard  Accessories  South  Bangalore  1677.74  2170.58   273.12
22    Smartwatch   Networking  North  Ahmedabad  2255.74   723.11  6234.51
87       Monitor    Computing  South    Chennai  2564.98  4139.07  8491.40
..           ...          ...    ...        ...      ...      ...      ...
994          NaN          NaN    NaN        NaN      NaN      NaN      NaN
995          NaN          NaN    NaN        NaN      NaN      NaN      NaN
996          NaN          NaN    NaN        NaN      NaN      NaN      NaN
997          NaN          NaN    NaN        NaN      NaN      NaN      NaN
998          NaN          NaN    NaN        NaN      NaN      NaN      NaN

[999 rows x 7 columns]

In [29]:
cf.sort_index()

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
3,Keyboard,Home Appliance,North,Kolkata,19937.50,3969.36,257.27
4,TV,Home Appliance,North,Delhi,NaN,1333.62,5011.02
...,...,...,...,...,...,...,...
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
cf.loc[0:4,['Region','Category']]

    Region        Category
0     West     Electronics
1  Central  Home Appliance
2     West     Accessories
3    North  Home Appliance
4    North  Home Appliance

In [31]:
cf.iloc[0:3,0:3]

  Product Name        Category   Region
0       Camera     Electronics     West
1   Headphones  Home Appliance  Central
2     Keyboard     Accessories     West

In [32]:
cf[cf['Sales']>20000]

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
6,Monitor,Home Appliance,North,Mumbai,45001.30,787.73,5897.50
7,Tablet,Electronics,South,Kolkata,48913.97,4269.88,7635.17
...,...,...,...,...,...,...,...
143,Tablet,Electronics,Central,Ahmedabad,24383.61,2595.56,9028.47
144,Smartwatch,Networking,East,Lucknow,22984.77,3004.30,5458.27
146,Headphones,Accessories,Central,Kolkata,29861.05,1785.61,6002.78
147,Tablet,Electronics,Central,Lucknow,44777.41,2925.60,1791.43
148,Keyboard,Computing,South,Jaipur,46602.45,1417.91,380.01

In [33]:
cf['Product Name'].str.lower()

0          camera
1      headphones
2        keyboard
3        keyboard
4              tv
          ...
994           NaN
995           NaN
996           NaN
997           NaN
998           NaN
Name: Product Name, Length: 999, dtype: object

In [34]:
pd.concat([cf.head(3),cf.tail(3)])

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
cf.drop_duplicates('Product Name')

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
4,TV,Home Appliance,North,Delhi,NaN,1333.62,5011.02
6,Monitor,Home Appliance,North,Mumbai,45001.30,787.73,5897.50
7,Tablet,Electronics,South,Kolkata,48913.97,4269.88,7635.17
9,Laptop,Networking,West,Mumbai,11524.77,1060.30,3240.32
15,Smartphone,Electronics,West,Chennai,NaN,2521.11,4754.80
17,Router,Accessories,NaN,Ahmedabad,49270.49,4894.30,7536.80
22,Smartwatch,Networking,North,Ahmedabad,2255.74,723.11,6234.51
150,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [36]:
df.drop(columns=['grade'])

                 name  class  age gender  marks
0        Aarav Sharma     10   15      M     92
1          Riya Verma      9   14      F     88
2        Vivaan Mehta      8   13      M     76
3         Anaya Gupta      7   12      F     95
4          Ishaan Rao     10   15      M     81
5          Diya Singh      9   14      F     67
6          Kabir Nair      8   13      M     72
7           Myra Jain      7   12      F     89
8         Arjun Patel     10   16      M     78
9            Sara Ali      9   14      F     93
10       Krish Pillai      8   13      M     85
11         Anvi Desai      7   12      F     91
12          Om Bansal     10   15      M     74
13        Tara Kapoor      9   14      F     98
14      Reyansh Yadav      8   13      M     69
15      Aadhya Saxena      7   12      F     87
16     Advik Kulkarni     10   15      M     96
17      Saanvi Shetty      9   14      F     77
18       Rudra Khatri      8   13      M     82
19        Kiara Joshi      7   12      F     90
20       Harsh Tiwari     10   16      M     63
21        Meera Menon      9   14      F     85
22     Laksh Malhotra      8   13      M     92
23        Navya Reddy      7   12      F     73
24      Shaurya Sethi     10   15      M     89
25         Aarohi Das      9   14      F     94
26         Dev Thakur      8   13      M     71
27        Inaaya Khan      7   12      F     86
28          Yug Arora     10   15      M     79
29          Pari Basu      9   14      F     64
30         Manan Vora      8   13      M     83
31        Amaira Paul      7   12      F     97
32       Atharv Sinha     10   16      M     88
33         Vanya Bhat      9   14      F     75
34      Aryan Gokhale      8   13      M     62
35        Shanaya Roy      7   12      F     80
36      Pranav Chopra     10   15      M     91
37       Zara Qureshi      9   14      F     84
38       Nivaan Kohli      8   13      M     77
39         Kavya Iyer      7   12      F     93
40         Arham Gill     10   16      M     68
41  Riddhi Chatterjee      9   14      F     88
42       Hridaan Garg      8   13      M     90
43        Mahika Puri      7   12      F     82
44     Shivansh Bhatt     10   15      M     74
45       Tanishka Rao      9   14      F     95
46      Ayaan D’Souza      8   13      M     87
47         Trisha Jha      7   12      F     79
48       Kiaan Oberoi     10   16      M     83
49      Nisha Solanki      9   14      F     92

In [37]:
df.rename(columns ={ 'marks':'score'})

                 name  class  age gender  score grade
0        Aarav Sharma     10   15      M     92     A
1          Riya Verma      9   14      F     88    B+
2        Vivaan Mehta      8   13      M     76    C+
3         Anaya Gupta      7   12      F     95    A+
4          Ishaan Rao     10   15      M     81     B
5          Diya Singh      9   14      F     67    D+
6          Kabir Nair      8   13      M     72     C
7           Myra Jain      7   12      F     89    B+
8         Arjun Patel     10   16      M     78    C+
9            Sara Ali      9   14      F     93     A
10       Krish Pillai      8   13      M     85    B+
11         Anvi Desai      7   12      F     91     A
12          Om Bansal     10   15      M     74     C
13        Tara Kapoor      9   14      F     98    A+
14      Reyansh Yadav      8   13      M     69    D+
15      Aadhya Saxena      7   12      F     87     B
16     Advik Kulkarni     10   15      M     96    A+
17      Saanvi Shetty      9   14      F     77    C+
18       Rudra Khatri      8   13      M     82     B
19        Kiara Joshi      7   12      F     90    A-
20       Harsh Tiwari     10   16      M     63     D
21        Meera Menon      9   14      F     85    B+
22     Laksh Malhotra      8   13      M     92     A
23        Navya Reddy      7   12      F     73     C
24      Shaurya Sethi     10   15      M     89    B+
25         Aarohi Das      9   14      F     94     A
26         Dev Thakur      8   13      M     71     C
27        Inaaya Khan      7   12      F     86     B
28          Yug Arora     10   15      M     79    C+
29          Pari Basu      9   14      F     64     D
30         Manan Vora      8   13      M     83     B
31        Amaira Paul      7   12      F     97    A+
32       Atharv Sinha     10   16      M     88    B+
33         Vanya Bhat      9   14      F     75    C+
34      Aryan Gokhale      8   13      M     62     D
35        Shanaya Roy      7   12      F     80    B-
36      Pranav Chopra     10   15      M     91     A
37       Zara Qureshi      9   14      F     84     B
38       Nivaan Kohli      8   13      M     77    C+
39         Kavya Iyer      7   12      F     93     A
40         Arham Gill     10   16      M     68    D+
41  Riddhi Chatterjee      9   14      F     88    B+
42       Hridaan Garg      8   13      M     90    A-
43        Mahika Puri      7   12      F     82     B
44     Shivansh Bhatt     10   15      M     74     C
45       Tanishka Rao      9   14      F     95    A+
46      Ayaan D’Souza      8   13      M     87     B
47         Trisha Jha      7   12      F     79    C+
48       Kiaan Oberoi     10   16      M     83     B
49      Nisha Solanki      9   14      F     92     A

In [38]:
df.sample(10)

                 name  class  age gender  marks grade
41  Riddhi Chatterjee      9   14      F     88    B+
12          Om Bansal     10   15      M     74     C
28          Yug Arora     10   15      M     79    C+
47         Trisha Jha      7   12      F     79    C+
24      Shaurya Sethi     10   15      M     89    B+
27        Inaaya Khan      7   12      F     86     B
4          Ishaan Rao     10   15      M     81     B
20       Harsh Tiwari     10   16      M     63     D
21        Meera Menon      9   14      F     85    B+
19        Kiara Joshi      7   12      F     90    A-

In [39]:
df.sample(10)

              name  class  age gender  marks grade
7        Myra Jain      7   12      F     89    B+
21     Meera Menon      9   14      F     85    B+
22  Laksh Malhotra      8   13      M     92     A
28       Yug Arora     10   15      M     79    C+
42    Hridaan Garg      8   13      M     90    A-
10    Krish Pillai      8   13      M     85    B+
38    Nivaan Kohli      8   13      M     77    C+
16  Advik Kulkarni     10   15      M     96    A+
24   Shaurya Sethi     10   15      M     89    B+
13     Tara Kapoor      9   14      F     98    A+

In [42]:
cf.isnull().sum()

Product Name    849
Category        849
Region          851
City            849
Sales           855
Price           851
Profit          849
dtype: int64

In [43]:
cf.dropna(how ='all')

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
3,Keyboard,Home Appliance,North,Kolkata,19937.50,3969.36,257.27
4,TV,Home Appliance,North,Delhi,NaN,1333.62,5011.02
...,...,...,...,...,...,...,...
145,Laptop,Networking,South,Pune,13041.72,3999.72,4969.87
146,Headphones,Accessories,Central,Kolkata,29861.05,1785.61,6002.78
147,Tablet,Electronics,Central,Lucknow,44777.41,2925.60,1791.43
148,Keyboard,Computing,South,Jaipur,46602.45,1417.91,380.01
149,Router,Electronics,South,Pune,16194.43,3755.77,5271.20

In [46]:
clean.isnull().sum()

Product Name    0
Category        0
Region          2
City            0
Sales           6
Price           2
Profit          0
dtype: int64

In [48]:
clean=cf.dropna(how ='all')

In [65]:
clean

,Product Name,Category,Region,City,Sales,Price,Profit
0,Camera,Electronics,West,Kolkata,46947.67,797.33,1733.15
1,Headphones,Home Appliance,Central,Hyderabad,42089.11,2238.05,1146.45
2,Keyboard,Accessories,West,Kolkata,35192.00,4528.89,503.32
3,Keyboard,Home Appliance,North,Kolkata,19937.50,3969.36,257.27
4,TV,Home Appliance,North,Delhi,NaN,1333.62,5011.02
...,...,...,...,...,...,...,...
145,Laptop,Networking,South,Pune,13041.72,3999.72,4969.87
146,Headphones,Accessories,Central,Kolkata,29861.05,1785.61,6002.78
147,Tablet,Electronics,Central,Lucknow,44777.41,2925.60,1791.43
148,Keyboard,Computing,South,Jaipur,46602.45,1417.91,380.01
149,Router,Electronics,South,Pune,16194.43,3755.77,5271.20

In [51]:
clean.mean(numeric_only = True)

Sales     25761.899653
Price      2644.088716
Profit     4653.781800
dtype: float64

In [52]:
clean.median(numeric_only = True)

Sales     24567.560
Price      2639.325
Profit     4724.585
dtype: float64

In [55]:
clean.mode(numeric_only = True)

       Sales    Price   Profit
0    1243.97   572.55   114.13
1    1279.46   579.90   121.72
2    1677.74   637.72   123.00
3    2255.74   655.01   132.81
4    2564.98   661.52   143.31
..       ...      ...      ...
145      NaN  4625.71  9508.35
146      NaN  4767.17  9648.52
147      NaN  4894.30  9730.82
148      NaN      NaN  9814.26
149      NaN      NaN  9879.31

[150 rows x 3 columns]

In [57]:
cleanmode = clean['Sales'].fillna(clean['Sales'].mode())

In [58]:
cleanmode

0      46947.67
1      42089.11
2      35192.00
3      19937.50
4       2564.98
         ...
145    13041.72
146    29861.05
147    44777.41
148    46602.45
149    16194.43
Name: Sales, Length: 150, dtype: float64

In [60]:
cleanmedian = clean['Sales'].fillna(clean['Sales'].median())

In [61]:
cleanmedian

0      46947.67
1      42089.11
2      35192.00
3      19937.50
4      24567.56
         ...
145    13041.72
146    29861.05
147    44777.41
148    46602.45
149    16194.43
Name: Sales, Length: 150, dtype: float64

In [62]:
cleanmode= clean['Sales'].fillna(clean['Sales'].mode())

In [64]:
cleanmode

0      46947.67
1      42089.11
2      35192.00
3      19937.50
4       2564.98
         ...
145    13041.72
146    29861.05
147    44777.41
148    46602.45
149    16194.43
Name: Sales, Length: 150, dtype: float64

In [1]:
a=10
b=20
cc=30

In [ ]:
if(a>b) & (a>c):
    print("ais the greatest")
          elif: (b>a) & (b>c):
    print